feat: disintegrate block
this-place/this.place pull request #86
Opened 2018-03-19 06:03 UTC by reginleiff

2018-03-19 07:27 UTC, nicholaschuayunzhi commented
@reginleiff are you able to come up with a more suitable name for this. Sounds very similar to fragile plugin? I'm sorry cant help much in this regard 😛

2018-03-19 07:48 UTC, reginleiff commented
@nicholaschuayunzhi Sorry, but are you referring to the interface `IDisplaceable` or the `Disintegrate` plugin?

2018-03-19 08:39 UTC, teclu commented
I propose DESTRUCTOBLOCK (in caps) as the block name.

2018-03-19 10:16 UTC, nicholaschuayunzhi commented
Was talking about the plugin. I like `IDisplaceable` though :-)

2018-03-19 10:17 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/IDisplaceable.cs
> +    bool IsMoveablePlugin();
I don't think we should have this.

2018-03-19 10:41 UTC, nicholaschuayunzhi requested changes
Hi @reginleiff, left some comments to make the code more concise.

2018-03-19 10:41 UTC, nicholaschuayunzhi commented on Assets/Scripts/PlayerMouse.cs
>                          : blockFaceOfNeighbouringBlock;
[1/2]
I realised this check is useless. Lets remove it. Line 86 - 87 already makes it such that `moveableFace` will always be `blockFaceOfNeighbouringBlock`

2018-03-19 10:41 UTC, nicholaschuayunzhi commented on Assets/Scripts/PlayerMouse.cs
>                          : blockFaceOfNeighbouringBlock;
[2/2]
We can then simply line `86 - 87` by creating another Method in `IDisplaceable`, something along the lines of 
```cs
// returns true if block can be displaced in the face direction provided
bool CanBeDisplaceInFaceDir(BlockFace)
```
Which does the appropriate check for moveable and disintegrate.

At the same time, we don't need `IDisplaceable#isDisplaced()`, `IDisplaceable#CanMove()`, `IDisplaceable#GetDisplacedFace()` any more with this change.

2018-03-19 10:41 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/MoveablePlugin.cs
> +
This doesnt seem very accurate as a block may not be able to be moved when it is translating.  But see my comments in `PlayerMouse` first.

2018-03-19 10:41 UTC, nicholaschuayunzhi commented on Assets/Scripts/BlockFaceBehaviour.cs
> +
remove the white space here 😅

2018-03-19 10:41 UTC, nicholaschuayunzhi commented on Assets/Scripts/BlockFaceBehaviour.cs
> +
remove whitespace here

2018-03-19 15:08 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/MoveablePlugin.cs
> +                return false;
can reduce nesting by return face.Equals(_displacedFace)

2018-03-19 15:12 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs
> +        } else if (!_block.IsTranslating())
style: newline here

2018-03-19 15:22 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/MoveablePlugin.cs
> +        }
white space here too

2018-03-19 15:23 UTC, nicholaschuayunzhi reviewed
This looks pretty cool. Some important notes, set the `disintegrate` material to the `UVMap` component in the `Distintegrate` block prefab. Otherwise the block will become grass (make sure to save and commit). Also i couldnt pull upwards, heard you were able to?

2018-03-19 15:26 UTC, nicholaschuayunzhi commented on Assets/Scripts/PlayerMouse.cs
> +                BlockFace moveableFace = blockFaceOfNeighbouringBlock;
we could just use blockFaceOfNieghbouringBlock.

2018-03-20 00:51 UTC, reginleiff commented
> we could just use blockFaceOfNieghbouringBlock.

Hmm, I left it there because it explained why we select it for highlighting, but I guess this removes a sort of redundant line.

> Set the disintegrate material to the UVMap component in the Distintegrate block prefab. Otherwise the block will become grass (make sure to save and commit). 

Needed it to test highlighting because the temporary material can't highlight :( 

> Also i couldnt pull upwards, heard you were able to?

No, I could not pull it up but the highlight would appear on the top even though I was not able to pull it.

2018-03-20 01:02 UTC, reginleiff commented
> I propose DESTRUCTOBLOCK (in caps) as the block name; DESTRUCTION (also in caps) as the Plugin.

> Sounds very similar to fragile 

I think the plugins describe the behaviour that it is inserting into the block, so what about `DestructiveProjectile`. `DESTRUCTION` kinda works though its a little vague imo.

2018-03-20 01:08 UTC, nicholaschuayunzhi commented
> Needed it to test highlighting because the temporary material can't highlight :(

Cant higlight because its not a texture atlas.

> No, I could not pull it up but the highlight would appear on the top even though I was not able to pull it.

It shouldnt highlight in the first place?

2018-03-20 01:09 UTC, nicholaschuayunzhi commented on Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs
> +        } else if (!_block.IsTranslating())
```
}
else if
}
```

2018-03-20 01:33 UTC, reginleiff commented
> It shouldnt highlight in the first place?

Okay I got it to work properly 👍 because the scene doesn't update the prefab -_-

2018-03-20 01:42 UTC, nicholaschuayunzhi approved these changes
Nice work

2018-03-20 01:43 UTC, merged